### PR TITLE
[DOC] API, Tutorials, Examples

### PR DESCRIPTION
**Pull request by ryanhammonds**
This adds a documentation site, similar to fooof/bycycle/ndsp. The difference is that the `nbsphinx` is used to generate tutorials/examples from jupyter notebooks. This allows "cell magic", i.e. bash in cells.

- [x] sphinx-quickstart + custom modifications
- [x] nbsphinx working with sphinx-gallery
- [x]  API finished
- [x] Finish tutorials

### CODE REVIEW

**Comment by voytek** [comment]
Just want to comment saying how _awesome_ this is looking. The interactives are excellent. Great work on this, @ryanhammonds!

**Comment by ryanhammonds** [comment]
Thank you! 😃 

The docsite is up here: https://voyteklab.com/ndspflow/

There are links example reports the bottom of the page.

**Comment by voytek** [comment]
Yep! Those are the ones I was playing around with. So good!

**Comment by ryanhammonds** [comment]
Glad you like it! :smile: 

I just realized the interactive cycle relabeling is broken on the docsite (which is really cool imo). Something to do with a javascript refactor that must have broke some paths to the custom js. I'll fix this soon.

**Pull request merged**
